name: "Test"

on: push

# Our test suite should cover:
# - Compatibility with the most recent versions of Python and Django
# - At least one test run for older supported version of Python and Django

# Current configuration:
# - python 3.9, django 4.0
# - python 3.8, django 3.2
# - python 3.7, django 3.1

jobs:
  lint:
    name: 🧹 Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
        with:
          python-version: 3.9
          cache: "pip"
          cache-dependency-path: "**/setup.cfg"
      - run: pip install black flake8 isort
      - name: Run flake8
        run: |
          # stop the build if there are Python syntax errors or undefined names
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
      - name: Run isort
        run: isort . --check-only --diff
      - name: Run black
        run: black . --check --fast

  test:
    name: 🧪 Test
    needs: lint
    runs-on: ubuntu-latest
    env:
      DJANGO_SETTINGS_MODULE: querystring_tag.testapp.settings
    strategy:
      matrix:
        include:
          - python: 3.9
            django: Django>=4.0,<5.0
            latest: true
          - python: 3.8
            django: Django>=3.2,<4.0
          - python: 3.7
            django: Django>=3.1,<3.2
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python }}
          cache: "pip"
          cache-dependency-path: "**/setup.cfg"
      - run: |
          pip install -e .[test]
          pip install "${{ matrix.django }}"
      - if: ${{ !matrix.latest }}
        run: pytest
      - if: ${{ matrix.latest }}
        run: pytest --junitxml=junit/test-results.xml --cov=querystring_tag
      - if: ${{ matrix.latest }}
        uses: codecov/codecov-action@v1
        with:
          name: Python 3.9
