name: "Test"

on: push

# Our test suite should cover:
# - Compatibility with the most recent versions of Python and Django
# - At least one test run for older supported version of Python and Django

# Current configuration:
# - python 3.11, django 4.1
# - python 3.10, django 4.0
# - python 3.9, django 3.2

jobs:
  lint:
    name: 🧹 Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: 3.11.1
          cache: "pip"
          cache-dependency-path: "**/setup.cfg"
      - run: pip install -e .[lint]
      - name: Run flake8
        run: |
          # stop the build if there are Python syntax errors or undefined names
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
      - name: Run isort
        run: isort . --check-only --diff
      - name: Run black
        run: black . --check --fast

  test:
    name: 🧪 Test
    needs: lint
    runs-on: ubuntu-latest
    env:
      DJANGO_SETTINGS_MODULE: querystring_tag.testapp.settings
    strategy:
      matrix:
        include:
          - name: dj4
            python-version: 3.11.1
            django-version: ">=4.1,<4.2"
            latest: true
          - name: dj32
            python-version: 3.10.9
            django-version: ">=3.2,<4.0"
          - name: dj31
            python-version: 3.9.16
            django-version: ">=3.1,<3.2"
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/setup.cfg') }}-${{ matrix.name }}
          restore-keys: ${{ runner.os }}-pip-
      - run: |
          pip install -e .[test]
          pip install "Django${{ matrix.django-version }}"
      - if: ${{ !matrix.latest }}
        run: pytest
      - if: ${{ matrix.latest }}
        run: pytest --junitxml=junit/test-results.xml --cov=querystring_tag
      - if: ${{ matrix.latest }}
        uses: codecov/codecov-action@v1
        with:
          name: Python 3.10
